name: gnrcdm

on:
  schedule:
    - cron: '56 */6 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "gnrcdm bot"
      
      - name: grab m3u files
        run: |
          pwd
          cd ./ressources/dmotion/py/gnrcpltfrm
          python3 gnrcpltfrm.py "x8dtuir" > lemedia.m3u8
          python3 gnrcpltfrm.py "x7zjeht" > cnbcar.m3u8
          python3 gnrcpltfrm.py "x5gv5rr" > c8.m3u8
          echo "m3u grabbed"
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "gnrcdm updated"
          git push
