name: nowtvtrfork

on:
  schedule:
    - cron: '03 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "nowtvtrfork bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests

      - name: Install streamlink module from forked repository
        run: python3 -m pip install git+https://github.com/ipstreet312/streamlink

      - name: fetch content nowtvtr
        run: |
          final_url=$(python3 ressources/tur/nowtvtr.py)
          echo "final_url=${final_url}" >> $GITHUB_ENV

      - name: Replace Text
        run: |
          content="${{ env.final_url }}"
          sed -i "\|net/nowtv| c ${content}" all.m3u
          sed -i "\|net/nowtv| c ${content}" ressources/allgr.m3u

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git add all.m3u ressources/allgr.m3u
          git commit -m "nowtvtrfork updated"
          git push
