name: tfdai action

on:
  schedule:
    - cron: '28 */3 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "tfdai bot"
      
      - name: updating tfdai
        run: python3 ressources/btv/py/tf1dai.py > ressources/btv/py/tf1dai.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull origin master
          git commit -m "tfdai updated"
          git push origin master
